"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";

export default function Consent() {
  const router = useRouter();
  const [mounted, setMounted] = useState(false);
  const [agreed, setAgreed] = useState(false);

  useEffect(() => {
    setMounted(true);
  }, []);

  return (
    <main className="flex min-h-screen flex-col items-center px-6 py-16">
      <div className="container-fluid">
        <Link
          href="/"
          data-mounted={mounted}
          className="reveal-fade text-sm text-muted transition-colors hover:text-foreground"
        >
          ← Krypta
        </Link>

        <h1
          data-mounted={mounted}
          style={{ animationDelay: "75ms" }}
          className="reveal text-fluid-h1 mt-8 text-balance font-medium leading-tight tracking-tight"
        >
          Before you enter.
        </h1>
        <p
          data-mounted={mounted}
          style={{ animationDelay: "150ms" }}
          className="reveal text-fluid-body mt-4 text-balance leading-relaxed text-muted"
        >
          KRYPTA is a hackathon prototype. Read what that actually means before continuing.
        </p>

        <section
          data-mounted={mounted}
          style={{ animationDelay: "225ms" }}
          className="reveal mt-10 rounded-2xl border border-border bg-surface p-6"
        >
          <h2 className="font-mono text-xs uppercase tracking-[0.15em] text-accent">
            Privacy
          </h2>
          <ul className="text-fluid-body mt-3 space-y-2 leading-relaxed text-muted">
            <li>KRYPTA operates exclusively in Alpaca&apos;s paper trading environment. No real funds are ever involved.</li>
            <li>Market and account data comes directly from Alpaca&apos;s API and is used only to run your session, never sold or shared.</li>
            <li>This is a hackathon prototype. Formal privacy practices for a production release have not been finalized.</li>
          </ul>
        </section>

        <section
          data-mounted={mounted}
          style={{ animationDelay: "300ms" }}
          className="reveal mt-4 rounded-2xl border border-border bg-surface p-6"
        >
          <h2 className="font-mono text-xs uppercase tracking-[0.15em] text-accent">
            Terms
          </h2>
          <ul className="text-fluid-body mt-3 space-y-2 leading-relaxed text-muted">
            <li>Nothing in KRYPTA is financial advice. Every thesis, risk assessment, and decision is generated by an AI system that can be wrong.</li>
            <li>All trading happens in Alpaca&apos;s paper environment only. No real orders, ever, during this hackathon.</li>
            <li>KRYPTA makes no claim of regulatory approval, licensing, or compliance certification of any kind.</li>
            <li>This software is prototype quality, provided as is, without warranty.</li>
          </ul>
        </section>

        <label
          data-mounted={mounted}
          style={{ animationDelay: "375ms" }}
          className="reveal mt-8 flex cursor-pointer items-start gap-3"
        >
          <input
            type="checkbox"
            checked={agreed}
            onChange={(e) => setAgreed(e.target.checked)}
            className="mt-0.5 h-4 w-4 shrink-0 rounded border-border bg-surface accent-accent"
          />
          <span className="text-fluid-body text-muted">
            I have read and agree to the Privacy summary and Terms above.
          </span>
        </label>

        <button
          type="button"
          disabled={!agreed}
          onClick={() => router.push("/onboarding")}
          data-mounted={mounted}
          style={{ animationDelay: "450ms" }}
          className="reveal mt-6 inline-flex w-full items-center justify-center rounded-full bg-accent px-8 py-3.5 text-sm font-medium text-background transition-all duration-150 ease-out hover:brightness-110 active:scale-[0.97] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-accent disabled:cursor-not-allowed disabled:bg-surface disabled:text-muted disabled:hover:brightness-100 disabled:active:scale-100 sm:w-auto"
        >
          Continue
        </button>
      </div>
    </main>
  );
}
